In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [7]:
arr / arr

C:\Users\abhis\AppData\Local\Temp\ipykernel_3248\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [9]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [10]:
np.log(arr)

C:\Users\abhis\AppData\Local\Temp\ipykernel_3248\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [11]:
arr.sum()

55

In [12]:
arr.max()

10

In [13]:
arr.mean()

5.0

In [14]:
arr.var()

10.0

In [15]:
arr.std()

3.1622776601683795

In [17]:
arr2d = np.arange(0,25).reshape(5,5)

In [18]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [20]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])