In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list = [[1, 2], [3, 4], [5, 6]]

In [5]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(2)

array([0.99573433, 0.66317061])

In [24]:
np.random.rand(4,5)

array([[0.90118988, 0.26670206, 0.0211535 , 0.73384871, 0.12145649],
       [0.9241483 , 0.78625187, 0.86969229, 0.28840452, 0.00325889],
       [0.93903041, 0.22862362, 0.01441895, 0.4563829 , 0.72241491],
       [0.28960025, 0.43652921, 0.09038852, 0.81081185, 0.37593472]])

In [31]:
np.random.randint(1, 100)

71

In [32]:
np.random.randint(1, 100, (2,3))

array([[44, 39, 33],
       [91, 85, 15]])

In [35]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
ranarr = np.random.rand(10)

In [38]:
ranarr

array([0.18182497, 0.18340451, 0.30424224, 0.52475643, 0.43194502,
       0.29122914, 0.61185289, 0.13949386, 0.29214465, 0.36636184])

In [41]:
ranarr.max()

0.6118528947223795

In [42]:
ranarr.argmax()

6

In [43]:
ranarr.min()

0.13949386065204183

In [44]:
ranarr.argmin()

7

In [45]:
ranarr.dtype

dtype('float64')