In [2]:
import numpy as np

In [4]:
arr = np.arange(0, 11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[:5]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [13]:
slice_of_arr[:3] = 99

In [14]:
slice_of_arr

array([99, 99, 99,  3,  4])

In [15]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_arr_copy = arr_copy[:5]

In [21]:
slice_of_arr_copy

array([0, 1, 2, 3, 4])

In [22]:
slice_of_arr_copy[:4] = 100

In [23]:
arr_copy

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[1, 1]

25

In [28]:
arr_2d[0, 2]

15

In [30]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
arr = np.arange(0, 11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [36]:
bool_arr = arr > 4

In [37]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [38]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])